"""add user_id to pattern

Revision ID: 67effbdcd406
Revises: 1983364a3793
Create Date: 2026-07-05 19:28:31.144181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67effbdcd406'
down_revision = '1983364a3793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pattern', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_pattern_pattern_name'), ['pattern_name'])
        batch_op.create_foreign_key(batch_op.f('fk_pattern_user_id_user'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_problem_problem_number'), ['problem_number'])
        batch_op.create_unique_constraint(batch_op.f('uq_problem_title'), ['title'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_phone_no'), ['phone_no'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_phone_no'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_problem_title'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_problem_problem_number'), type_='unique')

    with op.batch_alter_table('pattern', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_pattern_user_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_pattern_pattern_name'), type_='unique')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
