"""initial

Revision ID: a37b082e14ce
Revises: 
Create Date: 2026-07-10 17:37:41.210341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a37b082e14ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem',
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('problem_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('difficulty', sa.String(length=10), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('problem_id', name=op.f('pk_problem')),
    sa.UniqueConstraint('problem_number', name=op.f('uq_problem_problem_number')),
    sa.UniqueConstraint('title', name=op.f('uq_problem_title'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=70), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_no', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('phone_no', name=op.f('uq_user_phone_no')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    op.create_table('pattern',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pattern_name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_pattern_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pattern')),
    sa.UniqueConstraint('pattern_name', name=op.f('uq_pattern_pattern_name'))
    )
    op.create_table('user_problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.problem_id'], name=op.f('fk_user_problems_problem_id_problem'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_problems_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_problems'))
    )
    op.create_table('attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_problem_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('time_taken_mins', sa.Integer(), nullable=True),
    sa.Column('solved', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_problem_id'], ['user_problems.id'], name=op.f('fk_attempt_user_problem_id_user_problems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attempt'))
    )
    op.create_table('problem_pattern',
    sa.Column('user_problem_id', sa.Integer(), nullable=False),
    sa.Column('pattern_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pattern_id'], ['pattern.id'], name=op.f('fk_problem_pattern_pattern_id_pattern')),
    sa.ForeignKeyConstraint(['user_problem_id'], ['user_problems.id'], name=op.f('fk_problem_pattern_user_problem_id_user_problems')),
    sa.PrimaryKeyConstraint('user_problem_id', 'pattern_id', name=op.f('pk_problem_pattern'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problem_pattern')
    op.drop_table('attempt')
    op.drop_table('user_problems')
    op.drop_table('pattern')
    op.drop_table('user')
    op.drop_table('problem')
    # ### end Alembic commands ###
